### ISSUE TITLE
`JS Error => ReferenceError: P_[...]_0_show_ui is not defined` after upgrade to pyvista 0.42

### ISSUE THREAD

**Issue by francesco-ballarin** [pyvista/pyvista#4835]
### Describe the bug, what's wrong, and what you expected.

Hi, after upgrading an existing pyvista `0.41.x` installation to `0.42.0` I am not able anymore to show `trame` widgets in the browser.

Below the widget I have an error
``` JS Error => ReferenceError: P_0x7f3890fca490_0_show_ui is not defined```

and Chrome console says (only the probably relevant bits)
```
Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early

_loadFromKernel @ 150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1
bokeh-2.4.3.min.js:184 [bokeh] setting log level to: 'info'

:35515/paraview/:1     Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

app.93852572.js:1 Vue.use(vue_vtk, {}) - true - install(true)

app.93852572.js:1 Vue.use(trame_vuetify, {}) - true - install(true)

app.93852572.js:1 ReferenceError: P_0x7f3890fca490_0_show_ui is not defined
    at a.eval (eval at sc (vue.global.js:11:104811), <anonymous>:3:162)
    at t._render (vue.global.js:11:45499)
    at a.r (vue.global.js:11:79396)
    at t.get (vue.global.js:11:27998)
    at new t (vue.global.js:11:27911)
    at vue.global.js:11:79410
    at Cr.$mount (vue.global.js:11:79628)
    at Cr.$mount (vue.global.js:11:106970)
    at init (vue.global.js:11:33266)
    at vue.global.js:11:67703
```

I tried a complete reinstall of every `trame-*` package, but that didn't help. Any suggestion on what could have gone wrong in my upgrade?

### Steps to reproduce the bug.

None, it is probably specific to my system.

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Sat Sep 02 08:18:59 2023 CEST

                  OS : Linux
              CPU(s) : 8
             Machine : x86_64
        Architecture : 64bit
                 RAM : 15.3 GiB
         Environment : Jupyter
         File system : ext4
          GPU Vendor : Intel
        GPU Renderer : Mesa Intel(R) UHD Graphics 620 (WHL GT2)
         GPU Version : 4.6 (Core Profile) Mesa 23.1.6-1
    MathText Support : False

  Python 3.11.5 (main, Aug 26 2023, 18:28:17) [GCC 13.2.0]

             pyvista : 0.42.0
                 vtk : 9.2.6
               numpy : 1.24.2
          matplotlib : 3.6.3
              scooby : 0.7.1
               pooch : v1.7.0
              pillow : 10.0.0
             imageio : 2.26.0
               PyQt5 : 5.15.9
             IPython : 8.11.0
          ipywidgets : 8.0.4
               scipy : 1.10.1
                tqdm : 4.64.1
              meshio : 5.3.4
          jupyterlab : 3.6.1
               trame : 3.2.4
        trame_client : 2.11.2
        trame_server : 2.11.7
           trame_vtk : 2.5.8
       trame_vuetify : 2.3.1
jupyter_server_proxy : 4.0.0
        nest_asyncio : 1.5.6
--------------------------------------------------------------------------------
```

**Comment by tkoyama010** [comment]
Ping @annehaley

**Comment by MacGros** [comment]
Same here, I'm downgrading for the week :)

**Comment by tkoyama010** [comment]
Sorry. We will release 0.42.1 as soon as the problem is resolved.

**Comment by annehaley** [comment]
Hello @francesco-ballarin, thank you for pointing this out. It appears to be more than just your system, and I was able to replicate a similar error in my own environment. 

The error occurred when using the Trame Viewer widgets without calling the `ui` function. There is some state variable initialization in that function. Without initialization, the state variables would raise an error on attempt at retrieval. I made a draft PR (#4844) that simply declares default values for these state variables in the constructor. 

This simple adjustment fixed the instance of this error that I was able to get, and it may resolve yours. But I cannot be sure without further instructions on replication. Could you provide more code from your trame app?

**Comment by johannes-mueller** [comment]
I can show an example in binder which demonstrates the issue (or an related one)

https://mybinder.org/v2/gh/boschresearch/pylife/pyvista-trame?labpath=demos%2Fhotspot_beam.ipynb

**Comment by FelipeCybis** [comment]
Hi, cloning the repo and using the folllowing code works for me to reproduce the error in a jupyter environment.

```python
import pyvista as pv
from pyvista import examples

mesh = examples.load_random_hills()

pl = pv.Plotter()
pl.add_mesh(mesh)

pl.show()
```
I get `JS Error => ReferenceError: P_0x26c087c1390_0_show_ui is not defined`.

The solution in https://github.com/pyvista/pyvista/pull/4844 does not solve it for me.

Here is my `pv.Report()`:

Mon Sep 04 18:35:05 2023 Romance Daylight Time
OS | Windows | CPU(s) | 12 | Machine | AMD64
--- | --- | --- | --- | --- | ---
Architecture | 64bit | RAM | 63.9 GiB | Environment | Jupyter
GPU Vendor | VMware, Inc. | GPU Renderer | Gallium 0.4 on llvmpipe (LLVM 3.4, 128 bits) | GPU Version | 3.3 (Core Profile) Mesa 10.2.4 (git-d92815a)
MathText Support | False
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun 7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
pyvista | 0.42.dev0 | vtk | 9.2.6 | numpy | 1.25.2
matplotlib | 3.7.2 | scooby | 0.7.2 | pooch | v1.7.0
pillow | 10.0.0 | imageio | 2.31.2 | IPython | 8.15.0
colorcet | 3.0.1 | cmocean | v3.0.3 | ipywidgets | 8.1.0
meshio | 5.3.4 | trame | 3.2.4 | trame_client | 2.11.2
trame_server | 2.11.7 | trame_vtk | 2.5.8 | trame_vuetify | 2.3.1
jupyter_server_proxy | 4.0.0 | nest_asyncio | 1.5.7 |

**Comment by annehaley** [comment]
@francesco-ballarin @johannes-mueller  @FelipeCybis Thank you all for providing examples. I was able to test these and replicate the issue with all of them. I found a simple fix that resolved the problem on each of your examples when I tried them.
I added a new commit ([a9a2165](https://github.com/pyvista/pyvista/pull/4844/commits/a9a21659943f72fc3f72c8ec4bddcc02da50cd9d)) to the same PR. Please let me know if you are able to try this out.

**Comment by francesco-ballarin** [comment]
Thanks @annehaley for the quick fix! I confirm that the new commit fixes the issue on my end.

**Comment by johannes-mueller** [comment]
> I added a new commit ([a9a2165](https://github.com/pyvista/pyvista/pull/4844/commits/a9a21659943f72fc3f72c8ec4bddcc02da50cd9d)) to the same PR. Please let me know if you are able to try this out.

I can confirm that a9a21659943f72fc3f72c8ec4bddcc02da50cd9d fixes it for me. Thanks @annehaley.

**Comment by FelipeCybis** [comment]
LGTM :) thanks!
